apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.fullname" . }}-secrets
  labels:
    app: {{ include "laravel-app.name" . }}
type: Opaque
data:
  # Base64 encoded stubs for safety
  app-key: {{ "base64:3fH8D7w1PzH5v8v8qd7q5J7v7l4j7R9R4Z1K4E4Fo7I=" | b64enc }}
  db-password: {{ "SecretRootPassword123" | b64enc }}
