apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laravel-production-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hiteshv253/hiteshv253.git'
    targetRevision: HEAD
    path: docker-kubernetes-laravel/helm/laravel-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
