version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: k8s-laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      - APP_NAME="K8sLaravel"
      - APP_ENV=local
      - APP_KEY=base64:3fH8D7w1PzH5v8v8qd7q5J7v7l4j7R9R4Z1K4E4Fo7I=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_k8s
      - DB_USERNAME=root
      - DB_PASSWORD=SecretRootPassword123
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - k8s-network

  nginx:
    image: nginx:alpine
    container_name: k8s-laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - k8s-network

  mysql:
    image: mysql:8.0
    container_name: k8s-laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_k8s
      MYSQL_ROOT_PASSWORD: SecretRootPassword123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - k8s-network

  redis:
    image: redis:alpine
    container_name: k8s-laravel-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - k8s-network

volumes:
  mysql_data:
  redis_data:

networks:
  k8s-network:
    driver: bridge
