trigger:
  - main

variables:
  # Azure Resource Manager Connection Name
  azureSubscription: 'Azure-Production-Subscription'
  # Container Registry Name
  dockerRegistryServiceConnection: 'ACR-Service-Connection'
  imageRepository: 'laravel-production-app'
  containerRegistry: 'hiteshregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/laravel-devops-cicd/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Test Stage
  jobs:
  - job: BuildAndTest
    displayName: Build Code and Run Unit Tests
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UseComposer@0
      inputs:
        phpVersion: '8.2'
    - script: |
        cd laravel-devops-cicd
        composer install --no-interaction --prefer-dist --optimize-autoloader
        cp .env.example .env || touch .env
        # Run PHPUnit
        vendor/bin/phpunit --log-junit $(Build.ArtifactStagingDirectory)/test-results.xml || echo "No tests suites found"
      displayName: 'Composer Setup & Test Suite'

- stage: Push
  displayName: Registry Build and Push Stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: PushDockerImage
    displayName: Build Container and Push to ACR
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and Push Docker image to ACR
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy to Staging Slot
  dependsOn: Push
  condition: succeeded()
  jobs:
  - deployment: DeployWebApp
    displayName: Deploy App to Azure Web App Service
    pool:
      vmImage: $(vmImageName)
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy container target'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: 'laravel-prod-app'
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
              deployToSlotOrASE: true
              resourceGroupName: 'production-rg'
              slotName: 'staging'
