apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-resource-limits
  namespace: production
spec:
  hard:
    # CPU & RAM ceilings
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    # Count resources limits
    pods: "15"
    services: "10"
    persistentvolumeclaims: "5"
    configmaps: "15"
    secrets: "15"
