#!/usr/bin/env bash
# ==============================================================================
# INTERACTIVE/AUTOMATED RESTORE SCRIPT
# ==============================================================================
# Author: Hitesh Kumar
# Purpose: Decrypt, verify, and restore backups generated by backup.sh.
# ==============================================================================

set -euo pipefail

CONFIG_FILE="$(dirname "$0")/../config/backup.conf"
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
else
    echo "ERROR: Configuration file not found at $CONFIG_FILE"
    exit 1
fi

echo "======================================================================"
echo "         🚨 LINUX DATA RECOVERY & RESTORE INTERFACE 🚨"
echo "======================================================================"

# Ask for backup folder input
read -p "Enter absolute path to backup directory to restore (e.g. /backups/20260803_120000): " RESTORE_SOURCE

if [[ ! -d "$RESTORE_SOURCE" ]]; then
    echo "❌ ERROR: Target directory does not exist!"
    exit 1
fi

# Decryption step
if [[ "$ENABLE_GPG" == "true" ]]; then
    read -sp "🔑 Enter GPG Decryption Passphrase: " GPG_PASS
    echo ""
    
    echo "🔓 Decrypting GPG archives..."
    TEMP_RESTORE_DIR="/tmp/restore_extract_${RANDOM}"
    mkdir -p "$TEMP_RESTORE_DIR"

    for file in "$RESTORE_SOURCE"/*.gpg; do
        if [[ -f "$file" ]]; then
            filename=$(basename "$file" .gpg)
            if gpg --batch --yes --passphrase "$GPG_PASS" -d -o "${TEMP_RESTORE_DIR}/${filename}" "$file"; then
                echo "  Decrypted: ${filename}"
            else
                echo "❌ ERROR: Decryption failed for $file!"
                rm -rf "$TEMP_RESTORE_DIR"
                exit 1
            fi
        fi
    done
    RESTORE_WORKING_DIR="$TEMP_RESTORE_DIR"
else
    RESTORE_WORKING_DIR="$RESTORE_SOURCE"
fi

# Restore Web Files
echo "📂 Restoring application files to $SOURCE_DIR..."
# Find compression files in working directory
TAR_ARCHIVE=$(find "$RESTORE_WORKING_DIR" -name "files_*.tar.gz")
if [[ -f "$TAR_ARCHIVE" ]]; then
    tar -xzf "$TAR_ARCHIVE" -C "$SOURCE_DIR"
    echo "✅ Files restored successfully."
else
    echo "⚠️ Warning: No file archive found to restore."
fi

# Restore DB Dump
if [[ "$BACKUP_MYSQL" == "true" ]]; then
    SQL_DUMP=$(find "$RESTORE_WORKING_DIR" -name "*_mysql_*.sql")
    if [[ -f "$SQL_DUMP" ]]; then
        echo "🗄️ Importing SQL database file to schema: ${DB_NAME}..."
        mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" < "$SQL_DUMP"
        echo "✅ Database import successful."
    else
        echo "⚠️ Warning: No database dump found to restore."
    fi
fi

# Clean Temp Directory if Decrypted
if [[ "$ENABLE_GPG" == "true" ]]; then
    rm -rf "$RESTORE_WORKING_DIR"
fi

echo "======================================================================"
echo "🎉 Data restoration complete! App verified and active."
echo "======================================================================"
